document.writeln("	<div class=\'navbar navbar-default navbar-static-top\'>");
document.writeln("      <div class=\'container\'>");
document.writeln("        <div class=\'navbar-header\'>");
document.writeln("          <button type=\'button\' class=\'navbar-toggle\' data-toggle=\'collapse\' data-target=\'#navbar-ex-collapse\'>");
document.writeln("            <span class=\'sr-only\'>導航欄</span>");
document.writeln("            <span class=\'icon-bar\'></span>");
document.writeln("            <span class=\'icon-bar\'></span>");
document.writeln("            <span class=\'icon-bar\'></span>");
document.writeln("          </button>");
document.writeln("          <a class=\'navbar-brand\' href=\'/\'><span>永遠之夜-實況工作室 FNT Studio</span></a>");
document.writeln("        </div>");
document.writeln("        <div class=\'collapse navbar-collapse\' id=\'navbar-ex-collapse\'>");
document.writeln("          <ul class=\'nav navbar-nav navbar-right\'>");
document.writeln("            <li>");
document.writeln("              <a href=\'/\'>首頁</a>");
document.writeln("            </li>");
document.writeln("            <li>");
document.writeln("              <a href=\'/member\'>成員</a>");
document.writeln("            </li>");
document.writeln("          </ul>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </div>");