document.writeln("    <footer class=\'section section-primary\'>");
document.writeln("      <div class=\'container\'>");
document.writeln("        <div class=\'row\'>");
document.writeln("          <div class=\'col-sm-6\'>");
document.writeln("            <h1>關於本團隊</h1>");
document.writeln("            <p>FNT Studio 團長：");
document.writeln("              <a href=\'https://www.youtube.com/user/howard01222\' target=\'_blank\'><font color=\'#ffffff\'>薔薇 Rose</font></a>");
document.writeln("              <br>FNT Studio 副團長兼網站工程師：");
document.writeln("              <a href=\'https://www.youtube.com/channel/UCYLtQ2gBXAnG6WaurcoZ7kg?sub_confirmation=1\' target=\'_blank\'><font color=\'#ffffff\'>旋風之音 GoneTone</font></a>");
document.writeln("              <br>感謝各位貢獻者協助設計開發，我們開源在");
document.writeln("              <a href=\'https://github.com/FNTStudio/fntstudio.github.io\' target=\'_blank\'><font color=\'#ffffff\'>GitHub</font></a>");
document.writeln("            </p>");
document.writeln("          </div>");
document.writeln("          <div class=\'col-sm-6\'>");
document.writeln("            <p class=\'text-info text-right\'>");
document.writeln("              <br>");
document.writeln("              <br>");
document.writeln("            </p>");
document.writeln("            <div class=\'row\'>");
document.writeln("              <div class=\'col-md-12 hidden-lg hidden-md hidden-sm text-left\'>");
document.writeln("                <a href=\'https://www.facebook.com/forever.night.studio/\'><i class=\'fa fa-3x fa-fw fa-facebook text-inverse\'></i></a>");
document.writeln("                <a href=\'https://github.com/FNTStudio/fntstudio.github.io\' target=\'_blank\'><i class=\'fa fa-3x fa-fw fa-github text-inverse\'></i></a>");
document.writeln("              </div>");
document.writeln("            </div>");
document.writeln("            <div class=\'row\'>");
document.writeln("              <div class=\'col-md-12 hidden-xs text-right\'>");
document.writeln("                <a href=\'https://www.facebook.com/forever.night.studio/\' target=\'_blank\'><i class=\'fa fa-3x fa-fw fa-facebook text-inverse\'></i></a>");
document.writeln("                <a href=\'https://github.com/FNTStudio/fntstudio.github.io\' target=\'_blank\'><i class=\'fa fa-3x fa-fw fa-github text-inverse\'></i></a>");
document.writeln("              </div>");
document.writeln("            </div>");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </footer>");